import { NextResponse } from 'next/server';
import clientPromise from '../../../lib/mongodb';
import { ObjectId } from 'mongodb';

// Use separate key for journal generation
const GROQ_API_KEY = process.env.GROQ_API_KEY_INSIGHTS;
const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions';

export async function POST(request) {
    try {
        const { userId, date } = await request.json();

        if (!userId) {
            return NextResponse.json({ error: 'User ID required' }, { status: 400 });
        }

        const client = await clientPromise;
        const db = client.db('tara');
        const collection = db.collection('users');

        // Get user data
        const userData = await collection.findOne({ firebaseUid: userId });
        if (!userData) {
            return NextResponse.json({ error: 'User not found' }, { status: 404 });
        }

        // Get target date (default to today)
        const targetDate = date || new Date().toISOString().split('T')[0];

        // Check if journal already exists for this date
        const existingJournal = userData.journals?.find(j => j.date === targetDate && j.autoGenerated);
        if (existingJournal) {
            return NextResponse.json({
                success: true,
                journal: existingJournal,
                alreadyExists: true
            });
        }

        // Collect all chat messages from this date
        const chatUsers = userData.chatUsers || [];
        let dayMessages = [];

        chatUsers.forEach(chatUser => {
            const conversations = chatUser.conversations || [];
            conversations.forEach(msg => {
                const msgDate = new Date(msg.timestamp).toISOString().split('T')[0];
                if (msgDate === targetDate && msg.sender === 'user') {
                    dayMessages.push({
                        chatWith: chatUser.name,
                        content: msg.content,
                        time: msg.timestamp
                    });
                }
            });
        });

        // If no messages, return empty
        if (dayMessages.length === 0) {
            return NextResponse.json({
                success: false,
                message: 'No chat messages found for this date'
            });
        }

        // Sort by time
        dayMessages.sort((a, b) => new Date(a.time) - new Date(b.time));

        // Generate AI summary using Groq
        const summary = await generateJournalSummary(dayMessages, userData);

        // Create journal entry with unique _id
        const journalEntry = {
            _id: new ObjectId().toString(),
            date: targetDate,
            createdAt: new Date().toISOString(),
            title: `Daily Reflection - ${new Date(targetDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`,
            content: summary,
            tags: ['daily', 'auto-generated', 'reflection'],
            autoGenerated: true,
            messageCount: dayMessages.length
        };

        // Save to database
        await collection.updateOne(
            { firebaseUid: userId },
            {
                $push: { journals: journalEntry },
                $set: { lastUpdated: new Date() }
            }
        );

        return NextResponse.json({
            success: true,
            journal: journalEntry
        });

    } catch (error) {
        console.error('Journal generation error:', error);
        return NextResponse.json(
            { error: 'Failed to generate journal', details: error.message },
            { status: 500 }
        );
    }
}

async function generateJournalSummary(messages, userData) {
    try {
        // Build context from messages
        const messageText = messages.map((m, i) =>
            `${i + 1}. (with ${m.chatWith}): "${m.content}"`
        ).join('\n');

        const prompt = `You are TARA, an empathetic AI creating a personal daily journal entry.

Based on these chat messages from today, write a SHORT, personal reflection paragraph (3-4 sentences max) that:
- Captures the main emotions and themes of the day
- Sounds like the user wrote it themselves (first person: "I felt...", "Today I...")
- Is warm, reflective, and honest
- Mentions key moments or feelings without being too detailed

Chat messages from today:
${messageText}

Write a brief, heartfelt journal entry in first person:`;

        const groqResponse = await fetch(GROQ_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${GROQ_API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: 'llama-3.3-70b-versatile',
                messages: [{ role: 'user', content: prompt }],
                temperature: 0.7,
                max_tokens: 150
            }),
        });

        if (!groqResponse.ok) {
            throw new Error('Groq API failed');
        }

        const groqData = await groqResponse.json();
        let summary = groqData.choices[0]?.message?.content || '';

        // Clean up
        summary = summary.trim();
        if (summary.startsWith('"') && summary.endsWith('"')) {
            summary = summary.slice(1, -1);
        }

        return summary || 'Today I took time to reflect and connect with myself. It was a meaningful day of growth and self-discovery.';

    } catch (error) {
        console.error('Summary generation error:', error);
        return 'Today I took time to reflect and connect with myself. It was a meaningful day of growth and self-discovery.';
    }
}
