"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus, faPen, faChartLine, faBookOpen, faComments, faUser, faNewspaper, faBullseye, faWandSparkles } from "@fortawesome/free-solid-svg-icons";
import ProtectedRoute from "../components/ProtectedRoute";
import { useAuth } from "../contexts/AuthContext";
import { api } from "../../lib/api";
import BottomNav from "../components/BottomNav";

export default function JournalPage() {
  const { user } = useAuth();
  const [entries, setEntries] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [editing, setEditing] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  // Load journals from MongoDB
  useEffect(() => {
    if (user?.uid) {
      loadJournals();
    }
  }, [user]);

  const loadJournals = async () => {
    try {
      setLoading(true);
      const response = await api.get('/api/user-data');
      if (response.ok) {
        const data = await response.json();
        const journals = data.data?.journals || [];
        setEntries(journals);
      }
    } catch (error) {
      console.error('Error loading journals:', error);
    } finally {
      setLoading(false);
    }
  };

  const groups = useMemo(() => groupByDate(entries), [entries]);

  async function autoGenerateToday() {
    if (!user?.uid) return;

    const today = new Date().toISOString().split('T')[0];
    const alreadyExists = entries.some((e) => e.date === today && e.autoGenerated);

    if (alreadyExists) {
      alert('Today\'s journal already generated! 📝');
      return;
    }

    try {
      setGenerating(true);
      const response = await api.post('/api/journal-generate', {
        userId: user.uid,
        date: today
      });

      if (response.ok) {
        const data = await response.json();
        if (data.success) {
          setEntries((prev) => [data.journal, ...prev]);
          alert('✨ Daily journal generated from your chats!');
        } else {
          alert(data.message || 'No chat messages found for today');
        }
      }
    } catch (error) {
      console.error('Error generating journal:', error);
      alert('Failed to generate journal. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  return (
    <ProtectedRoute>
      <div className="flex min-h-screen flex-col bg-gradient-to-br from-rose-50 via-white to-rose-100">
        <header className="sticky top-0 z-10 border-b border-rose-100 bg-white/60 backdrop-blur">
          <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3">
            <Link href="/chatlist" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
              <img
                src="/taralogo.jpg"
                alt="Tara Logo"
                className="h-8 w-8 rounded-full object-cover"
              />
              <span className="text-lg font-semibold text-rose-600">Tara</span>
            </Link>

            {/* Profile Icon */}
            <Link href="/profile" className="rounded-full p-2 text-rose-600 hover:bg-rose-100 transition-colors">
              <FontAwesomeIcon icon={faUser} className="h-5 w-5" />
            </Link>

          </div>
        </header>

        <main className="mx-auto w-full max-w-5xl flex-1 px-4 py-6">
          <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
            <div className="text-base font-semibold text-gray-800">Your Journal</div>
            <div className="flex items-center gap-2">
              <button
                onClick={autoGenerateToday}
                disabled={generating}
                className="inline-flex items-center gap-2 rounded-full border border-rose-200 px-4 py-2 text-sm font-semibold text-rose-600 hover:bg-rose-200 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <FontAwesomeIcon icon={faWandSparkles} className={generating ? 'animate-spin' : ''} />
                {generating ? 'Generating...' : 'AI Generate Today'}
              </button>
              <button
                onClick={() => { setEditing(null); setShowModal(true); }}
                className="inline-flex items-center gap-2 rounded-full bg-rose-200 px-4 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-300 shadow-sm"
              >
                <FontAwesomeIcon icon={faPlus} /> Create Journal
              </button>
            </div>
          </div>
          {loading ? (
            <div className="text-center py-12 text-gray-500">Loading journals...</div>
          ) : groups.length === 0 ? (
            <EmptyState onNew={() => { setEditing(null); setShowModal(true); }} onGenerate={autoGenerateToday} />
          ) : (
            <div className="space-y-8">
              {groups.map(([date, items]) => (
                <section key={date}>
                  <h2 className="mb-3 text-xs font-bold uppercase tracking-wide text-rose-600">{date}</h2>
                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                    {items.map((e) => (
                      <article key={e.id} className="rounded-2xl border border-rose-100 bg-white p-4 shadow-sm">
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-2">
                            <div className="text-sm font-semibold text-gray-900">{e.title || "Untitled"}</div>
                            {e.autoGenerated && (
                              <span className="inline-flex items-center gap-1 rounded-full bg-purple-100 px-2 py-0.5 text-[10px] font-bold text-purple-600">
                                <FontAwesomeIcon icon={faWandSparkles} className="h-2 w-2" /> AI
                              </span>
                            )}
                          </div>
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => { setEditing(e); setShowModal(true); }}
                              className="inline-flex items-center gap-1 rounded-full border border-rose-200 px-3 py-1 text-xs font-semibold text-rose-600 hover:bg-rose-200"
                            >
                              <FontAwesomeIcon icon={faPen} /> Edit
                            </button>
                            <button
                              onClick={async () => {
                                if (confirm("Delete this journal?")) {
                                  try {
                                    const response = await api.delete('/api/journal', {
                                      userId: user.uid,
                                      journalId: e.id
                                    });
                                    if (response.ok) {
                                      setEntries((prev) => prev.filter((x) => x.id !== e.id));
                                    }
                                  } catch (error) {
                                    console.error('Error deleting journal:', error);
                                    alert('Failed to delete journal');
                                  }
                                }
                              }}
                              className="inline-flex items-center gap-1 rounded-full border border-rose-200 px-3 py-1 text-xs font-semibold text-rose-700 hover:bg-rose-50"
                            >
                              Delete
                            </button>
                          </div>
                        </div>
                        <p className="mt-2 whitespace-pre-wrap text-sm text-gray-700">{e.content}</p>
                        {e.tags?.length ? (
                          <div className="mt-3 flex flex-wrap gap-2">
                            {e.tags.map((t) => (
                              <span key={t} className="rounded-full bg-rose-200 px-2 py-1 text-[10px] font-bold text-rose-600">#{t}</span>
                            ))}
                          </div>
                        ) : null}
                      </article>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          )}
        </main>

        <BottomNav activePage="journal" />

        {showModal && (
          <JournalModal
            initial={editing}
            onClose={() => setShowModal(false)}
            onSave={async (payload) => {
              try {
                if (editing) {
                  // Update existing journal
                  const response = await api.put('/api/journal', {
                    userId: user.uid,
                    journalId: editing.id,
                    ...payload
                  });
                  if (response.ok) {
                    setEntries((prev) => prev.map((e) => (e.id === editing.id ? { ...e, ...payload } : e)));
                  }
                } else {
                  // Create new journal
                  const newJournal = {
                    id: `j${Date.now()}`,
                    date: new Date().toISOString().split('T')[0],
                    createdAt: new Date().toISOString(),
                    autoGenerated: false,
                    ...payload,
                  };

                  const response = await api.post('/api/journal', {
                    userId: user.uid,
                    journal: newJournal
                  });

                  if (response.ok) {
                    setEntries((prev) => [newJournal, ...prev]);
                  }
                }
                setShowModal(false);
              } catch (error) {
                console.error('Error saving journal:', error);
                alert('Failed to save journal');
              }
            }}
          />
        )}
      </div>
    </ProtectedRoute>
  );
}

function EmptyState({ onNew, onGenerate }) {
  return (
    <div className="flex min-h-[50vh] flex-col items-center justify-center gap-4 text-center">
      <div className="text-6xl mb-2">📝</div>
      <div className="text-xl font-semibold text-gray-800">Start your journal journey</div>
      <p className="max-w-md text-sm text-gray-600">Let AI create daily reflections from your chats, or write your own thoughts manually.</p>
      <div className="flex gap-3">
        <button onClick={onGenerate} className="rounded-full border-2 border-rose-300 px-5 py-3 text-sm font-semibold text-rose-600 hover:bg-rose-50 shadow-sm">
          <FontAwesomeIcon icon={faWandSparkles} /> AI Generate
        </button>
        <button onClick={onNew} className="rounded-full bg-rose-200 px-5 py-3 text-sm font-semibold text-rose-700 hover:bg-rose-300 shadow-sm">
          <FontAwesomeIcon icon={faPlus} /> Write Manually
        </button>
      </div>
    </div>
  );
}



function JournalModal({ initial, onClose, onSave }) {
  const [title, setTitle] = useState(initial?.title || "");
  const [content, setContent] = useState(initial?.content || "");
  const [tags, setTags] = useState(initial?.tags?.join(", ") || "");

  function submit(e) {
    e.preventDefault();
    const payload = {
      title: title.trim(),
      content: content.trim(),
      tags: tags
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean),
    };
    onSave(payload);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="w-full max-w-xl rounded-3xl border border-rose-100 bg-white p-6 shadow-xl">
        <div className="mb-4 text-lg font-bold text-gray-900">{initial ? "Edit Journal" : "New Journal"}</div>
        <form onSubmit={submit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700">Title</label>
            <input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="mt-1 w-full rounded-xl border border-rose-200 px-4 py-2 text-sm outline-none ring-rose-100 focus:ring"
              placeholder="Optional title"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Content</label>
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              rows={6}
              className="mt-1 w-full rounded-xl border border-rose-200 px-4 py-2 text-sm outline-none ring-rose-100 focus:ring"
              placeholder="Write your thoughts..."
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Tags (comma separated)</label>
            <input
              value={tags}
              onChange={(e) => setTags(e.target.value)}
              className="mt-1 w-full rounded-xl border border-rose-200 px-4 py-2 text-sm outline-none ring-rose-100 focus:ring"
              placeholder="growth, gratitude, reflection"
            />
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <button type="button" onClick={onClose} className="rounded-full border border-rose-200 px-4 py-2 text-sm font-medium text-rose-600 hover:bg-rose-200">
              Cancel
            </button>
            <button type="submit" className="rounded-full bg-rose-200 px-4 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-300 shadow-sm">
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function groupByDate(entries) {
  const fmt = (d) => new Date(d).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
  const map = new Map();

  // Sort entries by date (newest first)
  const sorted = [...entries].sort((a, b) => {
    const dateA = new Date(a.date || a.createdAt);
    const dateB = new Date(b.date || b.createdAt);
    return dateB - dateA;
  });

  for (const e of sorted) {
    const key = fmt(e.date || e.createdAt || Date.now());
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(e);
  }
  return Array.from(map.entries());
}


