import { NextResponse } from 'next/server';
import clientPromise from '../../../../lib/mongodb';
import { ObjectId } from 'mongodb';

const GROQ_API_KEY = process.env.GROQ_API_KEY;
const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions';
const CRON_SECRET = process.env.CRON_SECRET || 'your-secret-key-here';

/**
 * Daily Cron Job - Auto-generate journals for users
 * This endpoint should be called daily (e.g., at 11:59 PM)
 * 
 * Security: Requires CRON_SECRET in Authorization header
 * 
 * Usage:
 * - Vercel Cron: Configure in vercel.json
 * - External Cron: Call with Authorization header
 */
export async function GET(request) {
    try {
        // Verify cron secret for security
        const authHeader = request.headers.get('authorization');
        if (authHeader !== `Bearer ${CRON_SECRET}`) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        console.log('🕐 Starting daily journal auto-generation...');

        const client = await clientPromise;
        const db = client.db('tara');
        const users = db.collection('users');

        // Get yesterday's date (we generate journal for previous day)
        const yesterday = new Date();
        yesterday.setDate(yesterday.getDate() - 1);
        const targetDate = yesterday.toISOString().split('T')[0];

        console.log(`📅 Target date: ${targetDate}`);

        // Find all users who have chat activity but no journal for yesterday
        const allUsers = await users.find({
            chatUsers: { $exists: true, $ne: [] }
        }).toArray();

        console.log(`👥 Found ${allUsers.length} users with chat activity`);

        let processedCount = 0;
        let generatedCount = 0;
        let skippedCount = 0;
        let errorCount = 0;

        // Process each user
        for (const user of allUsers) {
            try {
                processedCount++;

                // Check if journal already exists for this date
                const existingJournal = user.journals?.find(
                    j => j.date === targetDate && j.autoGenerated
                );

                if (existingJournal) {
                    skippedCount++;
                    console.log(`⏭️  Skipped user ${user.firebaseUid} - journal already exists`);
                    continue;
                }

                // Collect chat messages from target date
                const chatUsers = user.chatUsers || [];
                let dayMessages = [];

                chatUsers.forEach(chatUser => {
                    const conversations = chatUser.conversations || [];
                    conversations.forEach(msg => {
                        const msgDate = new Date(msg.timestamp).toISOString().split('T')[0];
                        if (msgDate === targetDate && msg.sender === 'user') {
                            dayMessages.push({
                                chatWith: chatUser.name,
                                content: msg.content,
                                time: msg.timestamp
                            });
                        }
                    });
                });

                // Skip if no messages for this date
                if (dayMessages.length === 0) {
                    skippedCount++;
                    console.log(`⏭️  Skipped user ${user.firebaseUid} - no messages on ${targetDate}`);
                    continue;
                }

                // Sort messages by time
                dayMessages.sort((a, b) => new Date(a.time) - new Date(b.time));

                // Generate AI summary
                const summary = await generateJournalSummary(dayMessages, user);

                // Create journal entry
                const journalEntry = {
                    _id: new ObjectId().toString(),
                    date: targetDate,
                    createdAt: new Date().toISOString(),
                    title: `Daily Reflection - ${new Date(targetDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`,
                    content: summary,
                    tags: ['daily', 'auto-generated', 'reflection'],
                    autoGenerated: true,
                    messageCount: dayMessages.length
                };

                // Save to database
                await users.updateOne(
                    { firebaseUid: user.firebaseUid },
                    {
                        $push: { journals: journalEntry },
                        $set: { lastUpdated: new Date() }
                    }
                );

                generatedCount++;
                console.log(`✅ Generated journal for user ${user.firebaseUid} (${dayMessages.length} messages)`);

                // Add small delay to avoid rate limiting
                await new Promise(resolve => setTimeout(resolve, 1000));

            } catch (userError) {
                errorCount++;
                console.error(`❌ Error processing user ${user.firebaseUid}:`, userError);
            }
        }

        const result = {
            success: true,
            date: targetDate,
            stats: {
                totalUsers: allUsers.length,
                processed: processedCount,
                generated: generatedCount,
                skipped: skippedCount,
                errors: errorCount
            },
            timestamp: new Date().toISOString()
        };

        console.log('✨ Daily journal generation complete:', result);

        return NextResponse.json(result);

    } catch (error) {
        console.error('❌ Cron job error:', error);
        return NextResponse.json(
            {
                error: 'Cron job failed',
                details: error.message,
                timestamp: new Date().toISOString()
            },
            { status: 500 }
        );
    }
}

async function generateJournalSummary(messages, userData) {
    try {
        // Build context from messages
        const messageText = messages.map((m, i) =>
            `${i + 1}. (with ${m.chatWith}): "${m.content}"`
        ).join('\n');

        const prompt = `You are TARA, an empathetic AI creating a personal daily journal entry.

Based on these chat messages from today, write a SHORT, personal reflection paragraph (3-4 sentences max) that:
- Captures the main emotions and themes of the day
- Sounds like the user wrote it themselves (first person: "I felt...", "Today I...")
- Is warm, reflective, and honest
- Mentions key moments or feelings without being too detailed

Chat messages from today:
${messageText}

Write a brief, heartfelt journal entry in first person:`;

        const groqResponse = await fetch(GROQ_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${GROQ_API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: 'llama-3.3-70b-versatile',
                messages: [{ role: 'user', content: prompt }],
                temperature: 0.7,
                max_tokens: 150
            }),
        });

        if (!groqResponse.ok) {
            throw new Error('Groq API failed');
        }

        const groqData = await groqResponse.json();
        let summary = groqData.choices[0]?.message?.content || '';

        // Clean up
        summary = summary.trim();
        if (summary.startsWith('"') && summary.endsWith('"')) {
            summary = summary.slice(1, -1);
        }

        return summary || 'Today I took time to reflect and connect with myself. It was a meaningful day of growth and self-discovery.';

    } catch (error) {
        console.error('Summary generation error:', error);
        return 'Today I took time to reflect and connect with myself. It was a meaningful day of growth and self-discovery.';
    }
}

// POST endpoint for manual trigger (optional)
export async function POST(request) {
    return GET(request);
}
